<?php
	$bannerGroup = $this->setBannerGroupData($this->getData('banner_group'));
	$banners = $this->getCollection();
	
	if(count($banners) && $bannerGroup)
	{
		$bannerGroupIdentifier = $bannerGroup->getIdentifier();
?>
<div class="slider <?php echo ' ' . $bannerGroupIdentifier; ?>">
<?php
		foreach($banners as $banner)
		{
?>
    <img src="<?php echo $banner->getImage(); ?>" alt="<?php echo $banner->getTitle(); ?>" />
<?php
		}
?>
</div>
<?php 
	if($bannerGroup->getInitScript())
	{
?>
<script type="text/javascript">
	<?php echo $bannerGroup->getInitScript(); ?>
</script>
<?php
	}
	}
?>